### ISSUE TITLE
按博客里的教程测国内速度全是0

### ISSUE THREAD

**Issue by TheAutomatic** [isbasex/xbox-speed-test#2]
国外速度有高有低，国内全是0。可能不算issue吧，不过博客里好像没有评论区
下载速度排序
[ip] 221.228.216.59  [speed] 0.00 Mb/s
[ip] 59.63.235.26    [speed] 0.00 Mb/s
[ip] 122.228.119.219 [speed] 0.00 Mb/s
[ip] 122.228.119.247 [speed] 0.00 Mb/s
[ip] 122.228.119.238 [speed] 0.00 Mb/s
[ip] 183.131.60.153  [speed] 0.00 Mb/s
[ip] 101.71.75.77    [speed] 0.00 Mb/s
[ip] 59.63.235.11    [speed] 0.00 Mb/s
[ip] 58.216.96.13    [speed] 0.00 Mb/s
[ip] 180.96.3.138    [speed] 0.00 Mb/s
[ip] 58.216.106.236  [speed] 0.00 Mb/s

**Comment by isbasex** [comment]
@TheAutomatic 已经在 README 增加了自助更新 ip 的说明。最新代码已经更新部分国内 ip
